---
title: "Light and Dark Metabolomic Analysis"
author: "Sam Herr"
date: "2022-12-15"
output: html_document
---



```{r packages, include=FALSE}
library(readxl)
library(openxlsx)
library("nlme")
library(emmeans)
library(car)
library(lawstat)
library(tidyverse)
```
The below code chunks run analysis of metabolites from the light and dark experiment.
Each code chunk is basically the same except for different tissue types and differ by formatting issues.f

```{r 2018 embryo metabolites}

#input data.frame (replace location with where the file is located)
metabolite <- read.xlsx("data/EMBRYO_Tocos_Carots_Chlorophyll.xlsx",1)
#create new directory for plots and analysis outputs to live in
setwd("2018_embryo")

#data formatting
colnames(metabolite) <- metabolite[2,]
metabolite <-metabolite[-c(1,2),]
#selected only wanted phenotypes and format for further analysis
metabolite <- as.data.frame(metabolite[,c(4,5,7,14:30)])
metabolite <- metabolite[,!is.na(metabolite[1,])]
metabolite[,4:20] <- sapply(metabolite[,4:20], as.numeric)
len <- dim(metabolite)[2]
metabolite <- metabolite[order(metabolite$Genotype, metabolite$Treatment),]



#create basic plots for metabolites
metabolite.long <- metabolite %>% pivot_longer(!c(Treatment,rep,Genotype), names_to = "Metabolites", values_to = "Conc" )

ggplot(metabolite.long, aes(x = Conc, fill = Treatment )) + geom_histogram() +facet_wrap(~Metabolites, scales = "free")
ggsave("2018_metabolites.pdf")
ggplot(metabolite.long, aes(x = Genotype, y = Conc, color = Treatment )) + geom_point() +facet_wrap(~Metabolites, scales = "free")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggsave("2018_metabolites_Genotype.pdf", scale = 2)

ggplot(metabolite.long, aes(x = Treatment, y = Conc )) + geom_boxplot() +facet_wrap(~Metabolites, scales = "free")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggsave("2018_metabolites_Treatment.pdf", scale = 2)


#create data frames for levene's test, ANOVA, Tukeys, and BLUES
blues <- data.frame(matrix(nrow = 0, ncol = 4))
levene <- data.frame(matrix(nrow=2, ncol =17))
residuals <- data.frame(matrix(nrow = 42, ncol =0))
row.names(levene) <- c("genotype", "treatment")
names(levene) <- colnames(metabolite[,4:20])
genes_pval=data.frame(matrix(nrow=0,ncol=3))
names(genes_pval)=c('genotype',  'treatment','genotype:treatment')
tukey_pval=data.frame(matrix(nrow=0,ncol=3))
names(tukey_pval)=c('dark_control','light_control','light_dark')
tukey_pval_sliced=data.frame(matrix(nrow=0,ncol=21))
names(tukey_pval_sliced)=c("B73_dark_control","B73_light_control","B73_light_dark",
                           "B97_dark_control","B97_light_control","B97_light_dark",
                           "Ki11_dark_control","Ki11_light_control","Ki11_light_dark",
                           "M37W_dark_control","M37W_light_control","M37W_light_dark",
                           "MS71_dark_control","MS71_light_control","MS71_light_dark",
                           "NC358_dark_control","NC358_light_control","NC358_light_dark",
                           "OH7B_dark_control","OH7B_light_control","OH7B_light_dark")


#Perform ANOVA, tukey's HSD, levenes, and obtain residuals for every trait
for(i in 4:20){
  print(colnames(metabolite[i]))
  
  new_df = data.frame(y=metabolite[,i],treatment=metabolite$Treatment,rep=metabolite$rep, genotype = metabolite$Genotype)
  new_df$combine <- paste0(new_df$genotype,"_",new_df$rep)

 
  #Using different types of variance equality checks because of different sample size ine each group
   levene[1,i-3] <- lawstat::levene.test( new_df$y , new_df$genotype, location = "mean", correction.method = "correction.factor")$p.value
  levene[2,i-3] <- lawstat::levene.test( new_df$y, as.factor(new_df$treatment),location = "median")$p.value
  
  
 #different models for different heteroscedasticity
 #many outputs of singularity due to the rep random term. This because it has a variance of 0
 #for some of the phenotypes. Decided to leave in because little difference between left in and left out
  
  if(levene[1,i-3] < 0.05 || levene[2,i-3] < 0.05){
     if(levene[1,i-3] < levene[2,i-3]){
        metabolite_model <- lme(y ~ genotype*treatment, random = ~  1|combine, weights = varIdent(form=~1|genotype),  new_df)
     }else{
            metabolite_model <- lme(y ~ genotype*treatment, random = ~1|combine, weights = varIdent(form=~1|treatment),  new_df)
     }
  } else{
       metabolite_model <- lme(y ~ genotype*treatment, random = ~ 1|combine, new_df)
      
    }
 
  
  #save residual plots
  pdf(paste0(colnames(metabolite)[i]," Residuals.pdf"))
  print(plot(metabolite_model))
  print(plot( metabolite_model, genotype~resid(.), abline = 0 ))
  print(plot( metabolite_model, treatment~resid(.), abline = 0 ))
  print(plot(ranef(metabolite_model)))
  print(qqnorm(metabolite_model))
  dev.off()
  #studentized marginal residual (y - Xb)
  #level = 0 gets only fixed which inflates them greatly
  #the asreml uses STDCond, which are conditional standard errors.
  #So I choose to use conditional which has been used for outliers which is what we are doing 
  m <- resid(metabolite_model,type="pearson")


  residuals[,i-3] <- m / sqrt( (42-21-1 - m^2) / (42-21 - 2) )
 
  
  temp <- data.frame("genotype" =summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$genotype, "treatment" = summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$treatment, "trait" = rep(colnames(metabolite[i]) ,length(summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$SE)),"BLUE" =  summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$emmean, "SE" = summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$SE)
  
  blues <- rbind(blues, temp)

  #anova 
  a=anova(metabolite_model)
  genes_pval[i-3,]= a$`p-value`
  
  
  #Tukeys for treatment comparisons and save adjusted p-values
  #not trust worthy as this is always output
  #NOTE: Results may be misleading due to involvement in interactions
  print("Treatment")
  #b=emmeans(metabolite_model, list(pairwise ~ treatment), adjust = "tukey",lmer.df = "satterthwaite")
  metabolite_model.em <- emmeans(metabolite_model, ~genotype*treatment)
  b = mvcontrast(metabolite_model.em, "pairwise", mult.name = c("genotype"))
  tukey_pval[i-3,]=b$p.value
  
  print("Genotype")
  #tukey for treatment comparisons within genotypes and save adjusted p-values
  c <- summary(emmeans(metabolite_model, pairwise ~ treatment|genotype, adjust = "tukey",lmer.df = "satterthwaite"))
  tukey_pval_sliced[i-3,] <- p.adjust(c$contrasts$p.value, "BH")
  
  
}

#name rows with metabolites
row.names(genes_pval) <- colnames(metabolite)[4:20]
row.names(tukey_pval) <- colnames(metabolite)[4:20]
row.names(tukey_pval_sliced) <- colnames(metabolite)[4:20]
names(residuals) <- colnames(metabolite)[4:20]
row.names(residuals) <- paste(metabolite$Genotype, metabolite$Treatment, metabolite$rep,  sep ="_")

#create BLUE values in separate files
write.csv(blues, "embryo_2018_BLUEs.csv")


wb <- createWorkbook()

# Add sheets to the workbook
addWorksheet(wb, "ANOVA")
addWorksheet(wb, "Tukey")
addWorksheet(wb, "Nested Tukey")
addWorksheet(wb, "Cond Studentized Residuals")
addWorksheet(wb, "Levenes")
addWorksheet(wb, "BLUES")


writeData(wb, sheet = 1, genes_pval, startRow = 1, startCol = 1, rowNames = T)
writeData(wb, sheet = 2, tukey_pval, startRow = 1, startCol = 1, rowNames = T)
writeData(wb, sheet = 3, tukey_pval_sliced, startRow = 1, startCol = 1, rowNames = T)
writeData(wb, sheet = 4, residuals, startRow = 1, startCol = 1, rowNames = T)
writeData(wb, sheet = 5, levene, startRow = 1, startCol = 1, rowNames = T)
writeData(wb, sheet = 6, blues, startRow = 1, startCol = 1, rowNames = T)



# Save the workbook
saveWorkbook(wb, "data/2018_embryo_metabolites.xlsx", overwrite = TRUE)



```

```{r 2018 mature metabolites}
metabolite <- read.csv("data/1.L&D_averaged_2018.csv")
setwd("2018_mature")
#selected only wanted phenotypes
metabolite <- as.data.frame(metabolite[,-c(1,2,5,7,8,9,10,20,21)])
metabolite <-metabolite[,!is.na(metabolite[1,])]
metabolite[,4:12] <- sapply(metabolite[,4:12], as.numeric)
colnames(metabolite) <- gsub("[.]", "_",colnames(metabolite) )
len <- dim(metabolite)[2]
colnames(metabolite)[3] <- "Genotype"
metabolite <- metabolite[order(metabolite$Genotype, metabolite$Treatment),]



#create data frames for levene's test, ANOVA, Tukeys, and BLUES
blues <- data.frame(matrix(nrow = 0, ncol = 4))
levene <- data.frame(matrix(nrow=2, ncol =17))
residuals <- data.frame(matrix(nrow = 42, ncol =0))
row.names(levene) <- c("genotype", "treatment")
names(levene) <- colnames(metabolite[,4:12])

genes_pval=data.frame(matrix(nrow=0,ncol=3))
names(genes_pval)=c('genotype',  'treatment','genotype:treatment')
tukey_pval=data.frame(matrix(nrow=0,ncol=3))
names(tukey_pval)=c('dark_control','light_control','light_dark')
tukey_pval_sliced=data.frame(matrix(nrow=0,ncol=21))
names(tukey_pval_sliced)=c("B73_dark_control","B73_light_control","B73_light_dark",
                           "B97_dark_control","B97_light_control","B97_light_dark",
                           "Ki11_dark_control","Ki11_light_control","Ki11_light_dark",
                           "M37W_dark_control","M37W_light_control","M37W_light_dark",
                           "MS71_dark_control","MS71_light_control","MS71_light_dark",
                           "NC358_dark_control","NC358_light_control","NC358_light_dark",
                           "OH7B_dark_control","OH7B_light_control","OH7B_light_dark")


#loop through metabolites
for(i in 4:12){
  print(colnames(metabolite[i]))
  new_df = data.frame(y=metabolite[,i],treatment=metabolite$Treatment,rep=metabolite$Rep, genotype = metabolite$Genotype)
  new_df$combine <- paste0(new_df$genotype,"_",new_df$rep)

 
  #Using different types of variance equality checks because of different sample size ine each group
   levene[1,i-3] <- lawstat::levene.test( new_df$y , new_df$genotype, location = "mean", correction.method = "correction.factor")$p.value
  levene[2,i-3] <- lawstat::levene.test( new_df$y, as.factor(new_df$treatment),location = "median")$p.value
  
   #many outputs of singularity due to the rep random term. This because it has a variance of 0
  #for some of the phenotypes. Decided to leave in because little difference between left in and left out

  
 #different models for different heteroscedasticity
  if(levene[1,i-3] < 0.05 || levene[2,i-3] < 0.05){
     if(levene[1,i-3] < levene[2,i-3]){
        metabolite_model <- lme(y ~ genotype*treatment, random = ~  1|combine, weights = varIdent(form=~1|genotype),  new_df)
     }else{
            metabolite_model <- lme(y ~ genotype*treatment, random = ~1|combine, weights = varIdent(form=~1|treatment),  new_df)
     }
  } else{
       metabolite_model <- lme(y ~ genotype*treatment, random = ~ 1|combine, new_df)
      
    }
 
  
  #save residual plots
  pdf(paste0(colnames(metabolite)[i]," Residuals.pdf"))
  print(plot(metabolite_model))
  print(plot( metabolite_model, genotype~resid(.), abline = 0 ))
  print(plot( metabolite_model, treatment~resid(.), abline = 0 ))
  print(plot(ranef(metabolite_model)))
  print(qqnorm(metabolite_model))
  dev.off()
  #studentized marginal residual (y - Xb)
  #level = 0 gets only fixed which inflates them greatly
  #the asreml uses STDCond, which are conditional standard errors.
  #So I choose to use conditional which has been used for outliers which is what we are doing 
  m <- resid(metabolite_model,type="pearson")


  residuals[,i-3] <- m / sqrt( (42-21-1 - m^2) / (42-21 - 2) )
 
  
  temp <- data.frame("genotype" =summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$genotype, "treatment" = summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$treatment, "trait" = rep(colnames(metabolite[i]) ,length(summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$SE)),"BLUE" =  summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$emmean, "SE" = summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$SE)
  
  blues <- rbind(blues, temp)

  #anova 
  a=anova(metabolite_model)
  genes_pval[i-3,]= a$`p-value`
  
  
  #Tukeys for treatment comparisons and save adjusted p-values
  #not trust worthy as this is always output
  #NOTE: Results may be misleading due to involvement in interactions
  print("Treatment")
  #b=emmeans(metabolite_model, list(pairwise ~ treatment), adjust = "tukey",lmer.df = "satterthwaite")
  metabolite_model.em <- emmeans(metabolite_model, ~genotype*treatment)
  b = mvcontrast(metabolite_model.em, "pairwise", mult.name = c("genotype"))
  tukey_pval[i-3,]=b$p.value
  
  print("Genotype")
  #tukey for treatment comparisons within genotypes and save adjusted p-values
  c <- summary(emmeans(metabolite_model, pairwise ~ treatment|genotype, adjust = "tukey",lmer.df = "satterthwaite"))
  tukey_pval_sliced[i-3,] <- p.adjust(c$contrasts$p.value, "BH")
  
  
}

#name rows with metabolites
row.names(genes_pval) <- colnames(metabolite)[4:12]
row.names(tukey_pval) <- colnames(metabolite)[4:12]
row.names(tukey_pval_sliced) <- colnames(metabolite)[4:12]
colnames(residuals) <- colnames(metabolite)[4:12]
row.names(residuals) <- paste(metabolite$Genotype, metabolite$Treatment, metabolite$Rep,  sep ="_")
residuals <- as.data.frame(residuals)
levene <- levene[,1:9]


wb <- createWorkbook()

# Add sheets to the workbook
addWorksheet(wb, "ANOVA")
addWorksheet(wb, "Tukey")
addWorksheet(wb, "Nested Tukey")
addWorksheet(wb, "Cond Studentized Residuals")
addWorksheet(wb, "Levenes")
addWorksheet(wb, "BLUES")


writeDataTable(wb, sheet = 1, genes_pval, startRow = 1, startCol = 1, rowNames = T)
writeDataTable(wb, sheet = 2, tukey_pval, startRow = 1, startCol = 1, rowNames = T)
writeDataTable(wb, sheet = 3, tukey_pval_sliced, startRow = 1, startCol = 1, rowNames = T)
writeDataTable(wb, sheet = 4, residuals, startRow = 1, startCol = 1, rowNames = T)
writeDataTable(wb, sheet = 5, levene, startRow = 1, startCol = 1, rowNames = T)
writeDataTable(wb, sheet = 6, blues, startRow = 1, startCol = 1, rowNames = T)

# Rename the sheets

# Save the workbook
saveWorkbook(wb, "data/2018_mature_metabolites.xlsx", overwrite = TRUE, returnValue = T)



```

```{r 2019 mature metabolites}

metabolite <- read.csv("data/1.L&D_averaged_2019.csv")
setwd("2019_mature")

metabolite <- as.data.frame(metabolite[,-c(1,2,3,4,7,9,10,11,12,13,14,24,25,26)])
metabolite <-metabolite[,!is.na(metabolite[1,])]
metabolite[,4:12] <- sapply(metabolite[,4:12], as.numeric)
len <- dim(metabolite)[2]
colnames(metabolite)[3] <- "Genotype"
metabolite <- metabolite[order(metabolite$Genotype, metabolite$Treatment),]
metabolite.long <- metabolite %>% pivot_longer(!c(Treatment,Rep,Genotype), names_to = "Metabolites", values_to = "Conc" )

ggplot(metabolite.long, aes(x = Conc, fill = Treatment )) + geom_histogram() +facet_wrap(~Metabolites, scales = "free")
ggsave("2019_mature_metabolites.pdf")
ggplot(metabolite.long, aes(x = Genotype, y = Conc, color = Treatment )) + geom_point() +facet_wrap(~Metabolites, scales = "free")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggsave("2019_mature_metabolites_Genotype.pdf")


blues <- data.frame(matrix(nrow = 0, ncol = 4))
levene <- data.frame(matrix(nrow=2, ncol =9))
residuals <- data.frame(matrix(nrow = 17, ncol =0))
row.names(levene) <- c("genotype", "treatment")
names(levene) <- colnames(metabolite[,4:12])

genes_pval=data.frame(matrix(nrow=0,ncol=3))
names(genes_pval)=c('genotype',  'treatment','genotype:treatment')
tukey_pval=data.frame(matrix(nrow=0,ncol=3))
names(tukey_pval)=c('dark_control','light_control','light_dark')
tukey_pval_sliced=data.frame(matrix(nrow=0,ncol=9))
names(tukey_pval_sliced)=c("B73_dark_control","B73_light_control","B73_light_dark",
                           "B97_dark_control","B97_light_control","B97_light_dark",
                           
                           "OH7B_dark_control","OH7B_light_control","OH7B_light_dark")

#loop through metabolites
for(i in 4:12){
  print(colnames(metabolite[i]))
  new_df = data.frame(y=metabolite[,i],treatment=metabolite$Treatment,rep=metabolite$Rep, genotype = metabolite$Genotype)
  new_df$combine <- paste0(new_df$genotype,"_",new_df$rep)

  #many outputs of singularity due to the rep random term. This because it has a variance of 0
  #for some of the phenotypes. Decided to leave in because little difference between left in and left out
  #t <- mmer(y ~ genotype + treatment + genotype:treatment,
   #            random= ~ rep + rep:genotype,
    #          rcov= ~ vsr(dsr(genotype),units),
     #          data=new_df)
  
  #m <- data.frame(t$sigma)
  #m <- as.data.frame(rep(m[3:9], each = 6))
  levene[1,i-3] <- lawstat::levene.test( new_df$y , new_df$genotype, location = "mean", correction.method = "correction.factor")$p.value
  levene[2,i-3] <- lawstat::levene.test( new_df$y, as.factor(new_df$treatment),location = "median")$p.value
  
  
  
  if(levene[1,i-3] < 0.05 || levene[2,i-3] < 0.05){
     if(levene[1,i-3] < levene[2,i-3]){
        metabolite_model <- lme(y ~ genotype*treatment, random = ~ 1|combine, weights = varIdent(form=~1|genotype),  new_df)
     }else{
            metabolite_model <- lme(y ~ genotype*treatment, random = ~  1|combine, weights = varIdent(form=~1|treatment),  new_df)
     }
  } else{
       metabolite_model <- lme(y ~ genotype*treatment, random = ~  1|combine, new_df)
      
    }
 
  pdf(paste0(colnames(metabolite)[i],"mature_2019.pdf"))
  print(plot(metabolite_model))
  print(plot( metabolite_model, genotype~resid(.), abline = 0 ))
  print(plot( metabolite_model, treatment~resid(.), abline = 0 ))
  print(plot(ranef(metabolite_model)))
  print(qqnorm(metabolite_model))
  dev.off()
  #studentized marginal residual (y - Xb)
  #level = 0 gets only fixed effects however results in NA for studentized as standard error is smaller than        residuals which inflates them greatly
  #the asreml uses STDCond, which are conditional standard errors.
  #So I choose to use conditional which has been used for outliers which is what we are doing 
  m <- resid(metabolite_model,type="pearson")
  print(m)


  residuals[,i-3] <- m / sqrt( (42-21-1 - m^2) / (42-21 - 2) )
  nbind = 42 #non-missing observations
  fixed=3
  random=1
  threshold = qt(p= 1-0.05/(2*nbind), df=(nbind-(fixed+random+1)-1))
  #no outliers
  outliers <- sum(residuals >threshold)
  
  
  #blues
    temp <- data.frame("genotype" =summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$genotype, "treatment" = summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$treatment, "BLUE" =  summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$emmean, "trait" = rep(colnames(metabolite[i]) ,length(summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$SE)),"SE" = summary(emmeans(metabolite_model, pairwise ~ treatment|genotype)$emmeans)$SE)
  
  blues <- rbind(blues, temp)
  
  #anova 
   a=anova(metabolite_model)
  genes_pval[i-3,]= a$`p-value`
  
  #Tukeys for treatment comparisons and save adjusted p-values
  #not trust worthy as this is always output
  #NOTE: Results may be misleading due to involvement in interactions
  print("Treatment")
  #b=emmeans(fixed, list(pairwise ~ treatment), adjust = "tukey",lmer.df = "satterthwaite")
  fixed.em <- emmeans(metabolite_model, ~genotype*treatment)
  b = mvcontrast(fixed.em, "pairwise", mult.name = c("genotype"))
  tukey_pval[i-3,]=b$p.value
  
  print("Genotype")
  #tukey for treatment comparisons within genotypes and save adjusted p-values
  c <- summary(emmeans(metabolite_model, pairwise ~ treatment|genotype, adjust = "tukey",lmer.df = "satterthwaite"))
  tukey_pval_sliced[i-3,] <- p.adjust(c$contrasts$p.value, "BH")
  
  
}

 row.names(genes_pval) <- colnames(metabolite)[4:12]
row.names(tukey_pval) <- colnames(metabolite)[4:12]
row.names(tukey_pval_sliced) <- colnames(metabolite)[4:12]
names(residuals) <- colnames(metabolite)[4:12]
row.names(residuals) <- paste(metabolite$Genotype, metabolite$Treatment, metabolite$Rep,  sep ="_")

wb <- createWorkbook()

# Add sheets to the workbook
addWorksheet(wb, "ANOVA")
addWorksheet(wb, "Tukey")
addWorksheet(wb, "Nested Tukey")
addWorksheet(wb, "Cond Studentized Residuals")
addWorksheet(wb, "Levenes")
addWorksheet(wb, "BLUES")


writeData(wb, sheet = 1, genes_pval, startRow = 1, startCol = 1, rowNames = T)
writeData(wb, sheet = 2, tukey_pval, startRow = 1, startCol = 1, rowNames = T)
writeData(wb, sheet = 3, tukey_pval_sliced, startRow = 1, startCol = 1, rowNames = T)
writeData(wb, sheet = 4, residuals, startRow = 1, startCol = 1, rowNames = T)
writeData(wb, sheet = 5, levene, startRow = 1, startCol = 1, rowNames = T)
writeData(wb, sheet = 6, blues, startRow = 1, startCol = 1, rowNames = T)


# Rename the sheets

# Save the workbook
saveWorkbook(wb, "data/2019_mature_metabolites.xlsx", overwrite = TRUE)

```


